// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _1_DAL.DBContext;

#nullable disable

namespace _1_DAL.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20240314132553_dbInitall")]
    partial class dbInitall
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("_1_DAL.Models.Anh", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("DuongDan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaAnh")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Ten")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("ID");

                    b.HasIndex(new[] { "MaAnh" }, "UQ_Anh")
                        .IsUnique();

                    b.ToTable("Anh");
                });

            modelBuilder.Entity("_1_DAL.Models.ChatLieu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Ma" }, "UQ_ChatLieu")
                        .IsUnique();

                    b.ToTable("ChatLieu");
                });

            modelBuilder.Entity("_1_DAL.Models.ChucVu", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Ma" }, "UQ_ChucVu")
                        .IsUnique();

                    b.ToTable("ChucVu");
                });

            modelBuilder.Entity("_1_DAL.Models.DanhMuc", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid?>("IdDanhMucKhac")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdDanhMucKhac");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("Id");

                    b.HasIndex("IdDanhMucKhac");

                    b.HasIndex(new[] { "Ma" }, "UQ_DanhMuc")
                        .IsUnique();

                    b.ToTable("DanhMuc");
                });

            modelBuilder.Entity("_1_DAL.Models.DiaChi", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("DuongPho")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Huyen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("IdKhachHang")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdKhachHang");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ThanhPho")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("Xa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdKhachHang");

                    b.HasIndex(new[] { "Ma" }, "UQ_DiaChi")
                        .IsUnique();

                    b.ToTable("DiaChi");
                });

            modelBuilder.Entity("_1_DAL.Models.GiaoCa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChuPhatSinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdNvNhanCaTiep")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdNvTrongCa")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("ThoiGianGiaoCa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianNhanCa")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("TienBanDau")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TienPhatSinh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Time")
                        .HasColumnType("int");

                    b.Property<decimal?>("TongTienCaTruoc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TongTienKhac")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TongTienMat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TongTienMatRut")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TongTienTrongCa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdNvNhanCaTiep");

                    b.HasIndex(new[] { "Ma" }, "UQ_GiaoCa")
                        .IsUnique();

                    b.ToTable("GiaoCa");
                });

            modelBuilder.Entity("_1_DAL.Models.HoaDon", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdKh")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdKH");

                    b.Property<Guid?>("IdNv")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdNV");

                    b.Property<Guid?>("IdThanhToan")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdThanhToan");

                    b.Property<Guid?>("IdVouCher")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdVouCher");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MaGiamGia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayNhan")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayShip")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("date");

                    b.Property<string>("SDT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDTShip")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenShip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TienChuyenKhoan")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("TienKhachDua")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int?>("TinhTrang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.Property<decimal>("TongTienNvTrongCa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,0)")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("Id");

                    b.HasIndex("IdKh");

                    b.HasIndex("IdNv");

                    b.HasIndex("IdThanhToan");

                    b.HasIndex("IdVouCher");

                    b.HasIndex(new[] { "Ma" }, "UQ_HoaDon")
                        .IsUnique();

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("_1_DAL.Models.HoaDonChiTiet", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal?>("GiamGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValueSql("((0))");

                    b.Property<Guid?>("IdChiTietSanPham")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdChiTietSP");

                    b.Property<Guid?>("IdHoaDon")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdHoaDon");

                    b.Property<int?>("SoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.Property<decimal?>("ThanhTien")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdChiTietSanPham");

                    b.HasIndex("IdHoaDon");

                    b.ToTable("HoaDonChiTiet");
                });

            modelBuilder.Entity("_1_DAL.Models.KhachHang", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GioiTinh")
                        .HasColumnType("int");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("NamSinh")
                        .HasColumnType("date");

                    b.Property<string>("Sdt")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Ma" }, "UQ_KhachHang")
                        .IsUnique();

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("_1_DAL.Models.KieuDanhMuc", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid?>("IdDanhMuc")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdDanhMuc");

                    b.Property<Guid?>("IdSanPham")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdSanPham");

                    b.Property<int>("TheLoaiGioiTinh")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("Id");

                    b.HasIndex("IdDanhMuc");

                    b.HasIndex("IdSanPham");

                    b.ToTable("KieuDanhMuc");
                });

            modelBuilder.Entity("_1_DAL.Models.LoaiGiay", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Ma" }, "UQ_LoaiGiay")
                        .IsUnique();

                    b.ToTable("LoaiGiay");
                });

            modelBuilder.Entity("_1_DAL.Models.MauSac", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Ma" }, "UQ_MauSac")
                        .IsUnique();

                    b.ToTable("MauSac");
                });

            modelBuilder.Entity("_1_DAL.Models.NhanVien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<byte[]>("Anh")
                        .HasColumnType("image")
                        .HasColumnName("img");

                    b.Property<string>("CMND")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GioiTinh")
                        .HasColumnType("int");

                    b.Property<string>("Ho")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("IdCv")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdCV");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MaOTP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NamSinh")
                        .HasColumnType("date");

                    b.Property<string>("QueQuan")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TrangThai")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("Id");

                    b.HasIndex("IdCv");

                    b.HasIndex(new[] { "Ma" }, "UQ_NhanVien")
                        .IsUnique();

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("_1_DAL.Models.NhaSanXuat", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Ma" }, "UQ_NhaSanXuat")
                        .IsUnique();

                    b.ToTable("NhaSanXuat");
                });

            modelBuilder.Entity("_1_DAL.Models.SanPham", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid?>("IdChatLieu")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdChatLieu");

                    b.Property<Guid?>("IdNhaSanXuat")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdNhaSanXuat");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("Id");

                    b.HasIndex("IdChatLieu");

                    b.HasIndex("IdNhaSanXuat");

                    b.HasIndex(new[] { "Ma" }, "UQ_SanPham")
                        .IsUnique();

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("_1_DAL.Models.SanPhamChiTiet", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal?>("GiaBan")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,0)")
                        .HasDefaultValueSql("((0))");

                    b.Property<decimal?>("GiaNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,0)")
                        .HasDefaultValueSql("((0))");

                    b.Property<Guid?>("IdAnh")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdAnh");

                    b.Property<Guid?>("IdLoaiGiay")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdLoaiGiay");

                    b.Property<Guid?>("IdMauSac")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdMauSac");

                    b.Property<Guid?>("IdSanPham")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdSanPham");

                    b.Property<Guid?>("IdSizeGiay")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdSizeGiay");

                    b.Property<string>("MoTa")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("NamBh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NamBH")
                        .HasDefaultValueSql("((0))");

                    b.Property<int?>("SoLuongTon")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdAnh");

                    b.HasIndex("IdLoaiGiay");

                    b.HasIndex("IdMauSac");

                    b.HasIndex("IdSanPham");

                    b.HasIndex("IdSizeGiay");

                    b.ToTable("SanPhamChiTiet");
                });

            modelBuilder.Entity("_1_DAL.Models.SizeGiay", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("SoSize")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.Property<int>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Ma" }, "UQ_SizeGiay")
                        .IsUnique();

                    b.ToTable("SizeGiay");
                });

            modelBuilder.Entity("_1_DAL.Models.ThanhToan", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Ma" }, "UQ_ThanhToan")
                        .IsUnique();

                    b.ToTable("ThanhToan");
                });

            modelBuilder.Entity("_1_DAL.Models.Voucher", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal?>("GiaTriVoucher")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaGiamGia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("SoTienGiamGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenChuongTrinh")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "MaGiamGia" }, "UQ_MaGiamGia")
                        .IsUnique();

                    b.ToTable("Voucher");
                });

            modelBuilder.Entity("_1_DAL.Models.DanhMuc", b =>
                {
                    b.HasOne("_1_DAL.Models.DanhMuc", null)
                        .WithMany("IdDanhMucNavigation")
                        .HasForeignKey("IdDanhMucKhac");
                });

            modelBuilder.Entity("_1_DAL.Models.DiaChi", b =>
                {
                    b.HasOne("_1_DAL.Models.KhachHang", "IdKhachHangNavigation")
                        .WithMany("DiaChis")
                        .HasForeignKey("IdKhachHang")
                        .IsRequired();

                    b.Navigation("IdKhachHangNavigation");
                });

            modelBuilder.Entity("_1_DAL.Models.GiaoCa", b =>
                {
                    b.HasOne("_1_DAL.Models.NhanVien", "NhanVienNavigation")
                        .WithMany("GiaoCas")
                        .HasForeignKey("IdNvNhanCaTiep");

                    b.Navigation("NhanVienNavigation");
                });

            modelBuilder.Entity("_1_DAL.Models.HoaDon", b =>
                {
                    b.HasOne("_1_DAL.Models.KhachHang", "IdKhNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("IdKh")
                        .IsRequired();

                    b.HasOne("_1_DAL.Models.NhanVien", "IdNvNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("IdNv")
                        .IsRequired();

                    b.HasOne("_1_DAL.Models.ThanhToan", "IdThanhToanNavigration")
                        .WithMany("HoaDons")
                        .HasForeignKey("IdThanhToan")
                        .IsRequired();

                    b.HasOne("_1_DAL.Models.Voucher", "IdVoucherNavigration")
                        .WithMany("HoaDons")
                        .HasForeignKey("IdVouCher")
                        .IsRequired();

                    b.Navigation("IdKhNavigation");

                    b.Navigation("IdNvNavigation");

                    b.Navigation("IdThanhToanNavigration");

                    b.Navigation("IdVoucherNavigration");
                });

            modelBuilder.Entity("_1_DAL.Models.HoaDonChiTiet", b =>
                {
                    b.HasOne("_1_DAL.Models.SanPhamChiTiet", "IdChiTietSPNavigation")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("IdChiTietSanPham")
                        .IsRequired();

                    b.HasOne("_1_DAL.Models.HoaDon", "IdHoaDonNavigation")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("IdHoaDon")
                        .IsRequired();

                    b.Navigation("IdChiTietSPNavigation");

                    b.Navigation("IdHoaDonNavigation");
                });

            modelBuilder.Entity("_1_DAL.Models.KieuDanhMuc", b =>
                {
                    b.HasOne("_1_DAL.Models.DanhMuc", "IdDanhMucNavigation")
                        .WithMany("KieuDanhMucs")
                        .HasForeignKey("IdDanhMuc")
                        .IsRequired();

                    b.HasOne("_1_DAL.Models.SanPham", "IdHangHoaNavigation")
                        .WithMany("KieuDanhMucs")
                        .HasForeignKey("IdSanPham")
                        .IsRequired();

                    b.Navigation("IdDanhMucNavigation");

                    b.Navigation("IdHangHoaNavigation");
                });

            modelBuilder.Entity("_1_DAL.Models.NhanVien", b =>
                {
                    b.HasOne("_1_DAL.Models.ChucVu", "IdChucVuNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("IdCv")
                        .IsRequired();

                    b.Navigation("IdChucVuNavigation");
                });

            modelBuilder.Entity("_1_DAL.Models.SanPham", b =>
                {
                    b.HasOne("_1_DAL.Models.ChatLieu", "IdChatLieuNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("IdChatLieu")
                        .IsRequired();

                    b.HasOne("_1_DAL.Models.NhaSanXuat", "IdNhaSanXuatNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("IdNhaSanXuat")
                        .IsRequired();

                    b.Navigation("IdChatLieuNavigation");

                    b.Navigation("IdNhaSanXuatNavigation");
                });

            modelBuilder.Entity("_1_DAL.Models.SanPhamChiTiet", b =>
                {
                    b.HasOne("_1_DAL.Models.Anh", "IdAnhNavigation")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("IdAnh")
                        .IsRequired();

                    b.HasOne("_1_DAL.Models.LoaiGiay", "IdLoaiGiayNavigation")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("IdLoaiGiay")
                        .IsRequired();

                    b.HasOne("_1_DAL.Models.MauSac", "IdMauSacNavigation")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("IdMauSac")
                        .IsRequired();

                    b.HasOne("_1_DAL.Models.SanPham", "IdSanPhamNavigation")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("IdSanPham")
                        .IsRequired();

                    b.HasOne("_1_DAL.Models.SizeGiay", "IdSizeGiayNavigation")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("IdSizeGiay")
                        .IsRequired();

                    b.Navigation("IdAnhNavigation");

                    b.Navigation("IdLoaiGiayNavigation");

                    b.Navigation("IdMauSacNavigation");

                    b.Navigation("IdSanPhamNavigation");

                    b.Navigation("IdSizeGiayNavigation");
                });

            modelBuilder.Entity("_1_DAL.Models.Anh", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("_1_DAL.Models.ChatLieu", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("_1_DAL.Models.ChucVu", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("_1_DAL.Models.DanhMuc", b =>
                {
                    b.Navigation("IdDanhMucNavigation");

                    b.Navigation("KieuDanhMucs");
                });

            modelBuilder.Entity("_1_DAL.Models.HoaDon", b =>
                {
                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("_1_DAL.Models.KhachHang", b =>
                {
                    b.Navigation("DiaChis");

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("_1_DAL.Models.LoaiGiay", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("_1_DAL.Models.MauSac", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("_1_DAL.Models.NhanVien", b =>
                {
                    b.Navigation("GiaoCas");

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("_1_DAL.Models.NhaSanXuat", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("_1_DAL.Models.SanPham", b =>
                {
                    b.Navigation("KieuDanhMucs");

                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("_1_DAL.Models.SanPhamChiTiet", b =>
                {
                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("_1_DAL.Models.SizeGiay", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("_1_DAL.Models.ThanhToan", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("_1_DAL.Models.Voucher", b =>
                {
                    b.Navigation("HoaDons");
                });
#pragma warning restore 612, 618
        }
    }
}
